services:
  recorder:
    image: "binaryify/netease_cloud_music_api:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - "${WORK_SPACE_PATH}:/rec"
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
